
package BankIranWS.BankIranWS_NOR;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wsAcctStmtMessageSetPortType", targetNamespace = "http://v1.bankiran.org")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsAcctStmtMessageSetPortType {


    /**
     * 
     * @param msgMB60TOHOST
     * @return
     *     returns BankIranWS.BankIranWS_NOR.MB60MSGOUT
     * @throws FaultMsg
     */
    @WebMethod(operationName = "MB60_opr1", action = "http://v1.bankiran.org/MB60_opr1")
    @WebResult(name = "msg_MB60FROMHOST", targetNamespace = "http://v1.bankiran.org", partName = "msg_MB60FROMHOST")
    MB60MSGOUT mb60Opr1(
            @WebParam(name = "msg_MB60TOHOST", targetNamespace = "http://v1.bankiran.org", partName = "msg_MB60TOHOST")
                    MB60MSGIN msgMB60TOHOST)
        throws FaultMsg
    ;

    /**
     * 
     * @param msgFC04TOHOST
     * @return
     *     returns BankIranWS.BankIranWS_NOR.FC04MSGOUT
     * @throws FaultMsg
     */
    @WebMethod(operationName = "FC04_opr1", action = "http://v1.bankiran.org/FC04_opr1")
    @WebResult(name = "msg_FC04FROMHOST", targetNamespace = "http://v1.bankiran.org", partName = "msg_FC04FROMHOST")
    FC04MSGOUT fc04Opr1(
            @WebParam(name = "msg_FC04TOHOST", targetNamespace = "http://v1.bankiran.org", partName = "msg_FC04TOHOST")
                    FC04MSGIN msgFC04TOHOST)
        throws FaultMsg
    ;

    /**
     * 
     * @param msgFC87TOHOST
     * @return
     *     returns BankIranWS.BankIranWS_NOR.FC87MSGOUT
     * @throws FaultMsg
     */
    @WebMethod(operationName = "FC87_opr1", action = "http://v1.bankiran.org/FC87_opr1")
    @WebResult(name = "msg_FC87FROMHOST", targetNamespace = "http://v1.bankiran.org", partName = "msg_FC87FROMHOST")
    FC87MSGOUT fc87Opr1(
            @WebParam(name = "msg_FC87TOHOST", targetNamespace = "http://v1.bankiran.org", partName = "msg_FC87TOHOST")
                    FC87MSGIN msgFC87TOHOST)
        throws FaultMsg
    ;

    /**
     * 
     * @param msgFC44TOHOST
     * @return
     *     returns BankIranWS.BankIranWS_NOR.FC44MSGOUT
     * @throws FaultMsg
     */
    @WebMethod(operationName = "FC44_opr1", action = "http://v1.bankiran.org/FC44_opr1")
    @WebResult(name = "msg_FC44FROMHOST", targetNamespace = "http://v1.bankiran.org", partName = "msg_FC44FROMHOST")
    FC44MSGOUT fc44Opr1(
            @WebParam(name = "msg_FC44TOHOST", targetNamespace = "http://v1.bankiran.org", partName = "msg_FC44TOHOST")
                    FC44MSGIN msgFC44TOHOST)
        throws FaultMsg
    ;

    /**
     * 
     * @param msgFC02TOHOST
     * @return
     *     returns BankIranWS.BankIranWS_NOR.FC02MSGOUT
     * @throws FaultMsg
     */
    @WebMethod(operationName = "FC02_opr1", action = "http://v1.bankiran.org/FC02_opr1")
    @WebResult(name = "msg_FC02FROMHOST", targetNamespace = "http://v1.bankiran.org", partName = "msg_FC02FROMHOST")
    FC02MSGOUT fc02Opr1(
            @WebParam(name = "msg_FC02TOHOST", targetNamespace = "http://v1.bankiran.org", partName = "msg_FC02TOHOST")
                    FC02MSGIN msgFC02TOHOST)
        throws FaultMsg
    ;

}
