
package BankIranWS.BankIranWS_NOR;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wsAcctStmt_Service", targetNamespace = "http://v1.bankiran.org", wsdlLocation = "http://192.168.180.15:7836/wsAcctStmt_Service?wsdl")
public class WsAcctStmtService
    extends Service
{

    private final static URL WSACCTSTMTSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSACCTSTMTSERVICE_EXCEPTION;
    private final static QName WSACCTSTMTSERVICE_QNAME = new QName("http://v1.bankiran.org", "wsAcctStmt_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.180.15:7836/wsAcctStmt_Service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSACCTSTMTSERVICE_WSDL_LOCATION = url;
        WSACCTSTMTSERVICE_EXCEPTION = e;
    }

    public WsAcctStmtService() {
        super(__getWsdlLocation(), WSACCTSTMTSERVICE_QNAME);
    }

    public WsAcctStmtService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSACCTSTMTSERVICE_QNAME, features);
    }

    public WsAcctStmtService(URL wsdlLocation) {
        super(wsdlLocation, WSACCTSTMTSERVICE_QNAME);
    }

    public WsAcctStmtService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSACCTSTMTSERVICE_QNAME, features);
    }

    public WsAcctStmtService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsAcctStmtService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsAcctStmtMessageSetPortType
     */
    @WebEndpoint(name = "wsAcctStmt_Port")
    public WsAcctStmtMessageSetPortType getWsAcctStmtPort() {
        return super.getPort(new QName("http://v1.bankiran.org", "wsAcctStmt_Port"), WsAcctStmtMessageSetPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsAcctStmtMessageSetPortType
     */
    @WebEndpoint(name = "wsAcctStmt_Port")
    public WsAcctStmtMessageSetPortType getWsAcctStmtPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://v1.bankiran.org", "wsAcctStmt_Port"), WsAcctStmtMessageSetPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSACCTSTMTSERVICE_EXCEPTION!= null) {
            throw WSACCTSTMTSERVICE_EXCEPTION;
        }
        return WSACCTSTMTSERVICE_WSDL_LOCATION;
    }

}
